version: '3'
volumes:
  data:
services:
  db:
    container_name: ambient-weather-db
    hostname: ambient-weather-db
    image: mariadb:10.3
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ambient-weather
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3306:3306"
