name: "sftp deployment to hosting"

on:
  push:
    branches:
      - "main"

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: deploy file
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SERVER_USER }}
          server: ${{ secrets.SERVER_IP }}
          port: ${{ secrets.SERVER_PORT }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: "./server/build/*"
          remote_path: ${{ secrets.SERVER_PATH }}
          sftpArgs: "-o ConnectTimeout=5"
